# Generated by Django 4.2.7 on 2023-11-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=10)),
                ("gu", models.CharField(max_length=20)),
                ("nx", models.PositiveIntegerField()),
                ("my", models.PositiveIntegerField()),
            ],
        ),
    ]
