# Generated by Django 4.2.7 on 2023-11-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outer', models.CharField(max_length=50)),
                ('top', models.CharField(max_length=50)),
                ('pants', models.CharField(max_length=50)),
            ],
        ),
    ]
