# Generated by Django 4.2.7 on 2023-11-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalssi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='dol',
            field=models.ImageField(blank=True, null=True, upload_to='weather_images/'),
        ),
    ]
